### ISSUE TITLE
Select de la pantalla bono

### ISSUE THREAD

**Issue by sbenzt** [ProgramadoresFacet/CAVA#1]
En el select no deberia estar la opcion de pagar como autor porque si paga como autor, se va a guardar como que no tiene ningun trabajo, directamente tendrian que pagar en la pestaña "pagar trabajo como autor" total siempre va a ser 150, habria sacarlo del select pero no de la tabla, hacer alguna condicion para que no se muestre

**Comment by pablog20** [comment]
ya me fijo si puedo hacerlo

**Comment by pablog20** [comment]
listo. ya lo subo
